//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the kinco_control package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __kinco_control__MOTORCONFIG_H__
#define __kinco_control__MOTORCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace kinco_control
{
  class MotorConfigStatics;

  class MotorConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(MotorConfig &config, const MotorConfig &max, const MotorConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const MotorConfig &config1, const MotorConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, MotorConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const MotorConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, MotorConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const MotorConfig &config) const = 0;
      virtual void getValue(const MotorConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T MotorConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T MotorConfig::* field;

      virtual void clamp(MotorConfig &config, const MotorConfig &max, const MotorConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const MotorConfig &config1, const MotorConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, MotorConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const MotorConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, MotorConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const MotorConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const MotorConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, MotorConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, MotorConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<MotorConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(MotorConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("max_motor_rpm"==(*_i)->name){max_motor_rpm = boost::any_cast<int>(val);}
        if("gear_ratio"==(*_i)->name){gear_ratio = boost::any_cast<double>(val);}
        if("wheel_diameter"==(*_i)->name){wheel_diameter = boost::any_cast<double>(val);}
        if("wheels_x_distance"==(*_i)->name){wheels_x_distance = boost::any_cast<double>(val);}
        if("wheels_y_distance"==(*_i)->name){wheels_y_distance = boost::any_cast<double>(val);}
        if("left_motor_rpm"==(*_i)->name){left_motor_rpm = boost::any_cast<int>(val);}
        if("right_motor_rpm"==(*_i)->name){right_motor_rpm = boost::any_cast<int>(val);}
        if("lift_motor_rpm"==(*_i)->name){lift_motor_rpm = boost::any_cast<int>(val);}
      }
    }

    int max_motor_rpm;
double gear_ratio;
double wheel_diameter;
double wheels_x_distance;
double wheels_y_distance;
int left_motor_rpm;
int right_motor_rpm;
int lift_motor_rpm;

    bool state;
    std::string name;

    
}groups;



//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int max_motor_rpm;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double gear_ratio;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double wheel_diameter;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double wheels_x_distance;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double wheels_y_distance;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int left_motor_rpm;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int right_motor_rpm;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int lift_motor_rpm;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("MotorConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const MotorConfig &__max__ = __getMax__();
      const MotorConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const MotorConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const MotorConfig &__getDefault__();
    static const MotorConfig &__getMax__();
    static const MotorConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const MotorConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void MotorConfig::ParamDescription<std::string>::clamp(MotorConfig &config, const MotorConfig &max, const MotorConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class MotorConfigStatics
  {
    friend class MotorConfig;

    MotorConfigStatics()
    {
MotorConfig::GroupDescription<MotorConfig::DEFAULT, MotorConfig> Default("Default", "", 0, 0, true, &MotorConfig::groups);
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_motor_rpm = 0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_motor_rpm = 3000;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_motor_rpm = 300;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MotorConfig::AbstractParamDescriptionConstPtr(new MotorConfig::ParamDescription<int>("max_motor_rpm", "int", 0, "Maximum motor RPM", "", &MotorConfig::max_motor_rpm)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MotorConfig::AbstractParamDescriptionConstPtr(new MotorConfig::ParamDescription<int>("max_motor_rpm", "int", 0, "Maximum motor RPM", "", &MotorConfig::max_motor_rpm)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.gear_ratio = 1.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.gear_ratio = 20.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.gear_ratio = 2.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MotorConfig::AbstractParamDescriptionConstPtr(new MotorConfig::ParamDescription<double>("gear_ratio", "double", 0, "Gear ratio", "", &MotorConfig::gear_ratio)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MotorConfig::AbstractParamDescriptionConstPtr(new MotorConfig::ParamDescription<double>("gear_ratio", "double", 0, "Gear ratio", "", &MotorConfig::gear_ratio)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.wheel_diameter = 0.1;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.wheel_diameter = 1.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.wheel_diameter = 0.2;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MotorConfig::AbstractParamDescriptionConstPtr(new MotorConfig::ParamDescription<double>("wheel_diameter", "double", 0, "Wheel diameter (meters)", "", &MotorConfig::wheel_diameter)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MotorConfig::AbstractParamDescriptionConstPtr(new MotorConfig::ParamDescription<double>("wheel_diameter", "double", 0, "Wheel diameter (meters)", "", &MotorConfig::wheel_diameter)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.wheels_x_distance = 0.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.wheels_x_distance = 1.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.wheels_x_distance = 0.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MotorConfig::AbstractParamDescriptionConstPtr(new MotorConfig::ParamDescription<double>("wheels_x_distance", "double", 0, "Distance between wheels in X (meters)", "", &MotorConfig::wheels_x_distance)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MotorConfig::AbstractParamDescriptionConstPtr(new MotorConfig::ParamDescription<double>("wheels_x_distance", "double", 0, "Distance between wheels in X (meters)", "", &MotorConfig::wheels_x_distance)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.wheels_y_distance = 0.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.wheels_y_distance = 1.0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.wheels_y_distance = 0.1;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MotorConfig::AbstractParamDescriptionConstPtr(new MotorConfig::ParamDescription<double>("wheels_y_distance", "double", 0, "Distance between wheels in Y (meters)", "", &MotorConfig::wheels_y_distance)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MotorConfig::AbstractParamDescriptionConstPtr(new MotorConfig::ParamDescription<double>("wheels_y_distance", "double", 0, "Distance between wheels in Y (meters)", "", &MotorConfig::wheels_y_distance)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.left_motor_rpm = -3000;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.left_motor_rpm = 3000;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.left_motor_rpm = 0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MotorConfig::AbstractParamDescriptionConstPtr(new MotorConfig::ParamDescription<int>("left_motor_rpm", "int", 0, "RPM of the left motor", "", &MotorConfig::left_motor_rpm)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MotorConfig::AbstractParamDescriptionConstPtr(new MotorConfig::ParamDescription<int>("left_motor_rpm", "int", 0, "RPM of the left motor", "", &MotorConfig::left_motor_rpm)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.right_motor_rpm = -3000;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.right_motor_rpm = 3000;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.right_motor_rpm = 0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MotorConfig::AbstractParamDescriptionConstPtr(new MotorConfig::ParamDescription<int>("right_motor_rpm", "int", 0, "RPM of the right motor", "", &MotorConfig::right_motor_rpm)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MotorConfig::AbstractParamDescriptionConstPtr(new MotorConfig::ParamDescription<int>("right_motor_rpm", "int", 0, "RPM of the right motor", "", &MotorConfig::right_motor_rpm)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.lift_motor_rpm = -1000;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.lift_motor_rpm = 1000;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.lift_motor_rpm = 0;
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MotorConfig::AbstractParamDescriptionConstPtr(new MotorConfig::ParamDescription<int>("lift_motor_rpm", "int", 0, "RPM of the right motor", "", &MotorConfig::lift_motor_rpm)));
//#line 273 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MotorConfig::AbstractParamDescriptionConstPtr(new MotorConfig::ParamDescription<int>("lift_motor_rpm", "int", 0, "RPM of the right motor", "", &MotorConfig::lift_motor_rpm)));
//#line 245 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 245 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(MotorConfig::AbstractGroupDescriptionConstPtr(new MotorConfig::GroupDescription<MotorConfig::DEFAULT, MotorConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<MotorConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<MotorConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<MotorConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    MotorConfig __max__;
    MotorConfig __min__;
    MotorConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const MotorConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static MotorConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &MotorConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const MotorConfig &MotorConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const MotorConfig &MotorConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const MotorConfig &MotorConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<MotorConfig::AbstractParamDescriptionConstPtr> &MotorConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<MotorConfig::AbstractGroupDescriptionConstPtr> &MotorConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const MotorConfigStatics *MotorConfig::__get_statics__()
  {
    const static MotorConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = MotorConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __MOTORRECONFIGURATOR_H__
